language: ruby
rvm:
- 2.1.6
script:
- bundle exec rake --trace
before_deploy:
- bundle exec rake after_build --trace
deploy:
  provider: rubygems
  gem: osiris
  api_key:
    secure: HBa74rYy0YcYQ0KLyOIpgjUaa+rqPbUdkRnHJbMOjXZxZyfyCTKViQvygOtdMFjh/meptCqIuperimGDqudPQ9mAH6z+24D31epNWZvD5lI7QBMq+/lyKfdbJwH8dBq2eqOXs41t2ZI8kgeu75ASK4mRrk8uRzXImzFjAHYBxw5IILqKuC5XOhW9APAfmeKAKpfNZuidI6hc1y+vAsMLNiT9LsP2y8lxTR9s0nNUJcM5dpIwinb2AoV2hFJOumNZFurbFYfDBd5Y5iT0FHbfhtHr/+YbkTZbOFCanIr61aMBiluuETZU46GI9dm8G55JCl0UcNIdvoKMjBtbfk3KJOobsKpZ0WG3/Pgp8u/CIm54YliV6EhWjPCHefbH6IVPTSN8TQFv4wqyoxx0VkD03inWdAcX5hp9OD2uXjfghVFc8RzY/Y+1hCczZyb9YGTm1OWaJ8kSSho3H44tzoj3ZsRYtd/cq85mtvBS4Z7IbaTPgZZUnMf+0rbBJw37cIF7eOQpQhFJzgzJ3/IhfAo07Doyof9dV1llTQBn/HiFanoKOSdiyV75NtqH4mlCK1fLtwGzoLzYDsBl5Ua7yggzNyt7d+jP2VIkxgEw7DyvprRWG5JAudrrWb8+AFb9+C24rx32e8sfwUaollhuErzr4bi0HWzM425ROOdo/HtTlb4=
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH != master"
branches:
  only:
  - master
  - "/^release.*/"
env:
  global:
  - secure: KBfHoCHF/p3iP7XEVzsaUX80bwniYrBFAwHvx38sDXvavLOit7Y/P9hsWq/ufDqEYY+AtSrqv6aZFLQTVv2q+af1AsLAV0E3A2KnZwfRHpiLMzlhpN0UdiJiC4s5vMPg0EVRiKRiZonsENbUbr1OnSCqPI8EpZr1rPWN1d+26GL/YMD2TSkNWtylYeTVCKZIW0vSuTKU0CAfoL8qvWl+p6KgQ+XI7hFvJsoMF7jAJQKjILP/eWtVfLxX6UNcTDgKwod14hoCRSVAuXGgfx6q07vbt0HrFVKoV5/NhKcSoe2WUTTS8Ffsfb1VsfaaUYo8a8ImcYdA6e9y2JO+cgZrF/AItmYo1DRoNLVM5yknRhqq/FbNkIAVb20/2BO7fnUTpfHJV8KyodzP9IyQpxFhC0GxAMlIoO1BkUkcAmFGgALu9NS2+9zbFpNbnEPNGJcr9z8+pscY8V5VKARgJbVxCA6VCyUr6ip6sdCr0Y2vsIlZtzSrSp0Kie0QXkkEBE7jbrsjPwmgfF5NyHx0XfLqlzgsz6kLQf1ahTzQ680pEFoC2z+f4tRWfU3DgGw2pF08hT9q57saSb0DES61txUEw081NKBt4u7/5rbmwM1kfoVdrq0UegHIGo7BTF95As5XsZiPjvFdGP0Ke2G/i6v97Dij7ZdFPMqQCmicySxh6yI=
